version: '3.7'
services:
  nginx: 
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  flask-app:
    image: flask-app 
    build: ./
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
  mysql:
    image: database 
    build: ./application/models.py 
    ports: 
      - target: 3306
        published: 3306
        protocol: tcp
    volumes:
      - type: volume
        source: mysqlvolume
        target: /var/lib/mysql
volumes:
  mysqlvolume: